# Generated by Django 3.2.5 on 2021-07-08 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('project_name', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField()),
                ('body', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='yejinblog/')),
            ],
        ),
        migrations.CreateModel(
            name='Project_ing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ing', models.CharField(max_length=200)),
                ('project_name_ing', models.CharField(max_length=100)),
                ('pub_date_ing', models.DateTimeField()),
                ('body_ing', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='yejinblog/')),
            ],
        ),
    ]
