# Generated by Django 3.2.3 on 2021-07-03 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yejinblog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_date',
            new_name='project_name',
        ),
    ]
