# Generated by Django 3.2.5 on 2021-07-08 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yejinblog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project_ing',
            old_name='img',
            new_name='img_ing',
        ),
    ]
