# Generated by Django 3.2.5 on 2021-07-08 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yejinblog', '0002_rename_img_project_ing_img_ing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='detail/'),
        ),
    ]
