# Generated by Django 3.2.3 on 2021-07-05 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yejinblog', '0002_rename_project_date_project_project_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_ing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ing', models.CharField(max_length=200)),
                ('project_name_ing', models.CharField(max_length=100)),
                ('pub_date_ing', models.DateTimeField()),
                ('body_ing', models.TextField()),
            ],
        ),
    ]
