# Generated by Django 3.2.5 on 2021-07-08 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yejinblog', '0003_alter_project_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_title', models.CharField(blank=True, max_length=200, null=True)),
                ('study_link', models.URLField(verbose_name='Site URL')),
            ],
        ),
    ]
