# Generated by Django 3.2.5 on 2021-07-09 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yejinblog', '0005_auto_20210709_0414'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
